nohup: ignoring input
 * Debugger is active!
 * Debugger PIN: 665-917-752
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/cuc/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/cuc/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cuc/.local/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/cuc/.local/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/home/cuc/.local/lib/python3.8/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/home/cuc/.local/lib/python3.8/site-packages/django_extensions/management/commands/runserver_plus.py", line 294, in handle
    self.inner_run(options)
  File "/home/cuc/.local/lib/python3.8/site-packages/django_extensions/management/commands/runserver_plus.py", line 409, in inner_run
    run_simple(
  File "/home/cuc/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1063, in run_simple
    fd = int(os.environ["WERKZEUG_SERVER_FD"])
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'WERKZEUG_SERVER_FD'
